services:
    rabbitmq:
        image: "rabbitmq:3-management-alpine"
        ports:
            - 5672:5672
            - 15672:15672
    postgres:
        image: "postgres:13-alpine"
        environment:
            - POSTGRES_PASSWORD
        ports:
            - 5432:5432
        volumes:
            - ./init/database.sql:/docker-entrypoint-initdb.d/database.sql
    redis:
        image: "redis:6-alpine"
        ports:
            - 6379:6379
networks:
    default:
        name: microservices_network